# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-30 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_auto_20171130_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='deporte',
            field=models.CharField(blank=True, default='Baloncesto', max_length=25),
        ),
    ]
