# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-15 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0007_auto_20180214_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='id',
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(default='', max_length=70, primary_key=True, serialize=False),
        ),
    ]
