# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0008_auto_20180215_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(default='', max_length=70, primary_key=True, serialize=False, unique=True),
        ),
    ]
