# Generated by Django 2.0.3 on 2018-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0009_auto_20180215_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='deporte',
            field=models.CharField(blank=True, choices=[('Baloncesto', 'Baloncesto'), ('Voleibol', 'Voleibol'), ('Micro-Futbol', 'Micro-Futbol')], max_length=25, null=True),
        ),
    ]
