# Generated by Django 2.0.3 on 2018-04-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0011_auto_20180418_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='deporte',
            field=models.CharField(blank=True, choices=[('Baloncesto', 'Baloncesto'), ('Voleibol', 'Voleibol'), ('Micro-Futbol', 'Micro-Futbol')], default='Baloncesto', max_length=25, null=True),
        ),
    ]
