# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-30 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=1),
        ),
    ]
