# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-30 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_auto_20171130_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9),
        ),
    ]
