# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0008_remove_jugador_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='sexo',
            field=models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Femenino')], default='MAS', max_length=3),
            preserve_default=False,
        ),
    ]
