# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-30 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ronda', models.IntegerField()),
                ('cestasLocal', models.IntegerField()),
                ('cestasVisit', models.IntegerField()),
                ('faltasLocal', models.IntegerField()),
                ('faltasVisit', models.IntegerField()),
                ('equipoLoc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='equipo.Equipo')),
                ('equipoVis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='equipo.Equipo')),
            ],
        ),
    ]
