# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipoLoc',
            field=models.CharField(default='Equipo Local', max_length=30),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipoVis',
            field=models.CharField(default='Equipo Visitante', max_length=30),
        ),
    ]
