# Generated by Django 2.0.3 on 2018-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0002_auto_20180116_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipoLoc', models.CharField(default='', max_length=30)),
                ('equipoVis', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
