# Generated by Django 2.0.3 on 2018-03-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0003_fixture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
