# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-16 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_auto_20171130_0249'),
        ('equipo', '0002_auto_20171130_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='Torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneo.Torneo'),
        ),
    ]
