# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-16 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_equipo_torneo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='Torneo',
            new_name='torneo',
        ),
    ]
