# Generated by Django 2.0.3 on 2018-03-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_auto_20180309_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
