# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_auto_20180213_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=35, primary_key=True, serialize=False, unique=True),
        ),
    ]
